/*-----------------------------------------*/
/*	DROP DATABASE HAN_SQL_EXAM_DATABASE    */
/*-----------------------------------------*/

/*WARNING! IF YOU RUN THIS SCRIPT, THE WHOLE DATABASE
WITH ALL THE DATA WILL BE DELETED, ONLY USE THIS FOR THE TESTING ENVIROMENT!*/

DROP DATABASE IF EXISTS HAN_SQL_EXAM_DATABASE
GO